# 服务器配置
server:
  mode: "release"                             # 运行模式
  port: "8088"                                # 端口
  token_expire_time: 3600                     # JWT token 过期时间
  allowed_refers: ["localhost", "127.0.0.1"]  # 允许的 referer
# 数据库配置
db:
  host: "mysql"           # 主机地址
  user_name: "root"       # 用户名
  password: "19960331"    # 密码
  database: "aries"       # 数据库名
  port: "3306"            # 端口
  time_zone: "Local"      # 时区
  max_idle_conn: 10       # 最大空闲连接数
  max_open_conn: 20       # 最大打开连接数
# smtp 配置（仅用于重置密码）
smtp:
  address: "smtp.qq.com"       # 协议地址
  port: 465                    # 端口
  account: "1040970792@qq.com" # 帐号
  password: "" # 密码