definitions:
  form.CategoryAddForm:
    properties:
      name:
        description: 分类名称
        type: string
      parent_id:
        description: 父级分类 ID
        type: integer
      type:
        description: 分类类型，默认值为 0 表文章；1 表友链
        type: integer
      url:
        description: 访问 URL
        type: string
    required:
    - name
    - url
    type: object
  form.CategoryEditForm:
    properties:
      id:
        type: integer
      name:
        description: 分类名称
        type: string
      parent_id:
        description: 父级分类 ID
        type: integer
      type:
        description: 分类类型，默认值为 0 表文章；1 表友链
        type: integer
      url:
        description: 访问 URL
        type: string
    required:
    - name
    - url
    type: object
  form.LoginForm:
    properties:
      captcha_id:
        description: 验证码 ID
        type: string
      captcha_val:
        description: 验证码
        type: string
      pwd:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - captcha_id
    - captcha_val
    - pwd
    - username
    type: object
  form.RegisterForm:
    properties:
      email:
        description: 邮箱
        type: string
      pwd:
        description: 密码
        type: string
      second_pwd:
        description: 确认密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - email
    - pwd
    - second_pwd
    - username
    type: object
  form.TagAddForm:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  form.TagEditForm:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  util.Result:
    properties:
      code:
        description: 状态码
        example: 100
        type: integer
      data:
        description: 数据
        type: object
      msg:
        description: 提示
        example: 密码错误
        type: string
    type: object
host: localhost:8088
info:
  contact: {}
  description: Aries 开源博客项目 API 接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin Swagger
  version: "1.0"
paths:
  /api/v1/all_categories:
    get:
      consumes:
      - application/json
      parameters:
      - description: 分类类型
        in: query
        name: category_type
        required: true
        type: integer
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 获取所有分类
      tags:
      - 分类
  /api/v1/all_tags:
    get:
      consumes:
      - application/json
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 获取所有标签
      tags:
      - 标签
  /api/v1/auth/captcha:
    get:
      consumes:
      - application/json
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 创建验证码
      tags:
      - 授权
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录表单
        in: body
        name: loginForm
        required: true
        schema:
          $ref: '#/definitions/form.LoginForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 登录
      tags:
      - 授权
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册表单
        in: body
        name: regForm
        required: true
        schema:
          $ref: '#/definitions/form.RegisterForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 注册
      tags:
      - 授权
  /api/v1/categories:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ids
        in: query
        name: ids
        required: true
        type: string
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 批量删除分类
      tags:
      - 分类
    get:
      consumes:
      - application/json
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页条数
        in: query
        name: size
        type: integer
      - description: 关键词
        in: query
        name: key
        type: string
      - description: 分类类型
        in: query
        name: category_type
        required: true
        type: integer
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 分页获取分类数据
      tags:
      - 分类
    post:
      consumes:
      - application/json
      parameters:
      - description: 添加分类表单
        in: body
        name: addForm
        required: true
        schema:
          $ref: '#/definitions/form.CategoryAddForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 添加分类
      tags:
      - 分类
    put:
      consumes:
      - application/json
      parameters:
      - description: 修改分类表单
        in: body
        name: editForm
        required: true
        schema:
          $ref: '#/definitions/form.CategoryEditForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 修改分类
      tags:
      - 分类
  /api/v1/categories/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 删除分类
      tags:
      - 分类
  /api/v1/parent_categories:
    get:
      consumes:
      - application/json
      parameters:
      - description: 分类类型
        in: query
        name: category_type
        required: true
        type: integer
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 获取所有父级分类
      tags:
      - 分类
  /api/v1/tags:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ids
        in: query
        name: ids
        required: true
        type: string
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 批量删除标签
      tags:
      - 标签
    get:
      consumes:
      - application/json
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页条数
        in: query
        name: size
        type: integer
      - description: 关键词
        in: query
        name: key
        type: string
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 分页获取标签
      tags:
      - 标签
    post:
      consumes:
      - application/json
      parameters:
      - description: 添加标签表单
        in: body
        name: addForm
        required: true
        schema:
          $ref: '#/definitions/form.TagAddForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 添加标签
      tags:
      - 标签
    put:
      consumes:
      - application/json
      parameters:
      - description: 修改标签表单
        in: body
        name: editForm
        required: true
        schema:
          $ref: '#/definitions/form.TagEditForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 修改标签
      tags:
      - 标签
  /api/v1/tags/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 删除标签
      tags:
      - 标签
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/util.Result'
        "104":
          schema:
            $ref: '#/definitions/util.Result'
      summary: 根据 ID 获取标签
      tags:
      - 标签
swagger: "2.0"
